rlarjsdn3/EST-Soft-Team3-3rd-Project

- Health.xcodeproj/project.pbxproj
- Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Health/Application/AppDelegate.swift
- Health/Core/Protocols/StoryboardInstantiable.swift
- Health/Core/Utils/NSObject+ID.swift
- Health/Core/Utils/NSObject+Nib.swift
close #5 
---
- UIStoryboard에서 쉽게 `UIViewController` 객체를 생성할 수 있도록 `UIStoryboardInstantiable` 프로토콜 (기본) 구현 코드 작성
- 예를 들어, 아래 예제는 Main 스토리보드에 정의되어 있는 initialViewController를 로드하는 코드입니다.
```swift
let vc = MainViewController.instantitateIntialViewController(name: "Main")
```
- 하지만, 세그웨이를 통해 화면 간 전환을 할 것이므로, 자주 쓰이는 코드는 아니라 생각합니다. 사용할 일이 있을까 해서 작성하였습니다.
- 뷰 및 스토리보드 객체에 해당하는 UINib 객체를 불러와주는 코드 구현, 클래스 이름으로 문자열 ID 값을 생성해주는 코드 구현
```swift
collectionView.register(nib: MainCollectionViewCell.nib, identifier: MainCollectionViewCell.id)
```
- 모두 컬렉션 뷰에 셀의 Nib 및 ID 등록을 편하게 하려는 목적으로 작성된 코드입니다.
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
> feat: `StoryboardInstantiable` 및 `NSObject+Nib`, `NSObject+ID` 확장 코드 구현

- Health/Application/Configuration/AppConfiguration.swift
- Health/Core/Network/APIEndpoint.swift
- Health/Core/Network/HTTPValidationError.swift
- Health/Core/Network/NetworkError.swift
- Health/Core/Network/NetworkService.swift
Alan AI API 요청을 위한 공통 네트워크 서비스 모듈을 구현했습니다.
SSE 및 Mock 대응 이전 단계로, URLSession + Swift Concurrency 기반 구조를 설정했습니다.
- Mock 데이터 대응
- SSE 스트리밍 응답 대응
- Alan AI 종속성 분리 및 추상화
- [태스크 (노션)](https://www.notion.so/oreumi/241ebaa8982b80838cc7d65426b242c5?source=copy_link)
> feat: 네트워크 공통 서비스 기본 구조 도입

- Health/Application/Configuration/AppConfiguration.swift
- Health/Core/Network/DefaultNetworkService.swift
- Health/Core/Network/NetworkService.swift
- 네이밍 피드백을 잘못 적용한 점을 수정했습니다.
- 프로토콜과 클래스를 별도의 파일로 분리했습니다.
NetworkService.swift
ㄴ 프로토콜: `DefaultNetworkService`
ㄴ 클래스: `NetworkService`
NetworkService.swift
ㄴ 프로토콜: `NetworkService`
DefaultNetworkService.swift
ㄴ 클래스: `DefaultNetworkService`
- [노션 태스크](https://www.notion.so/oreumi/242ebaa8982b804f9810e2eea12b6ece?v=23eebaa8982b80c28518000ce135dcc4&source=copy_link)
> refactor: 네트워크 서비스의 프로토콜 / 기본 클래스 이름 변경 및 파일 분리

- .gitignore
- Health.xcodeproj/project.pbxproj
- Health/Resources/Info.plist
>  해당 없음 (팀 API 키 관리 설정)
---
- Secrets.xcconfig에서 API 키를 안전하게 읽어오는 기능 구현
- Info.plist의 `AlanCurrentClientID` 값을 Bundle에서 읽어와 반환
---
- **Secrets.xcconfig 파일이 필요합니다** (별도 공유 예정)
- Info.plist에 `AlanCurrentClientID` 키 설정 확인 필요
- 프로젝트 Configuration에 Secrets.xcconfig 연결 확인
- 빌드 전 xcconfig 설정이 올바른지 검증 필요
---
- `AppConfiguration.clientID` 프로퍼티 라고 AppConfiguration 코드 파일에 clientID 키 설정하는 것 코드 작업자 분이 추가해주세요.
```swift
// 사용 예시
let endpoint = APIEndpoint.ask(
content: "테스트 질문",
clientID: AppConfiguration.clientID
)
```
> feat: Secrets.xcconfig와 Info.plist 연동으로 API 키 보안 관리 구현

- Health/Application/Configuration/AppConfiguration.swift
- Health/Model/Alan/AlanQuestionResponse.swift
- Health/Model/Alan/AlanResetStateResponse.swift
- Health/Model/Alan/AlanStreamingResponse.swift
- Health/Presentation/Alan/AlanViewModel.swift
- Health/Presentation/Base.lproj/Main.storyboard
- 달력 탭 이름을 "캘린더"로 변경
- Alan API 응답 모델 추가
- `AlanQuestionResponse.swift`
- `AlanStreamingResponse.swift`
- `AlanResetStateResponse.swift`
- Alan API 뷰모델 추가 (SSE 제외)
- `AlanViewModel.swift`
- [노션 태스크](https://www.notion.so/oreumi/Alan-API-245ebaa8982b80caa8d1cd77a460848e?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
- [xcconfig](https://www.notion.so/oreumi/xcconfig-241ebaa8982b80149419dd8ba6a7186e?source=copy_link)
> feat: Alan API 응답 모델 및 뷰모델 추가

- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.xib
- 캘린더 탭 월별 달력에 연월 타이틀 추가
- 요일 행 (일요일부터 토요일까지) 추가
| CalendarMonthCell 스토리보드 | 시뮬레이터 |
| -- | -- |
| <img width="540" height="245" alt="image" src="https://github.com/user-attachments/assets/d5ec6e9a-b4cf-4f60-bd05-d0c004ae2d3f" /> | <img width="603" height="1311" alt="simulator_screenshot_7A23CCDC-F568-469B-A62D-EB6815C670F7" src="https://github.com/user-attachments/assets/ad3f0874-d2ba-42e1-8f24-86aa3fbe8917" /> |
- [노션 태스크](https://www.notion.so/oreumi/245ebaa8982b802a9268dc6bfde69a97?source=copy_link)
> feat: 캘린더 탭 연월 타이틀 및 요일 행 추가

- Health/DesignSystem/Constant/UIView+CornerRadius.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Views/CalendarDateCell.swift
- Health/Presentation/Calendar/Views/CalendarDateCell.xib
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.xib
- Health/Presentation/Calendar/Views/CalendarProgressBar.swift
아이폰/아이패드에서 캘린더 탭 진입시 혹은 가로/세로 변경시
- 각 날짜의 원형배경 (CircleView) 제대로 표시
- 달력 아래부분이 짤리지 않도록 높이 조정
- 각 날짜 사이 간격 조정
- 월별 셀 높이 동적 조정
> 폰트 크기는 추후 논의 후 적용
| Before | After |
| -- | -- |
| <img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/51eaba94-cd3e-4f8f-abd6-b4ac58b09a6e" /> | <img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/f617a294-b412-4b0e-95f4-451e7d1a768e" /> |
| Before | After |
| -- | -- |
| <img width="1640" height="2360" alt="image" src="https://github.com/user-attachments/assets/2c82c758-baef-476c-bd38-af39de245b5a" /> | <img width="1640" height="2360" alt="image" src="https://github.com/user-attachments/assets/a3602446-37f2-4aae-8acc-3f8b97f7407c" /> |
| Before | After |
| -- | -- |
| <img …
> fix: 캘린더 탭 패드 가로/세로 대응

- .gitignore
- Health.xcodeproj/project.pbxproj
- Health/Application/AppDelegate.swift
- Health/Application/Configuration/AppConfiguration.swift
- Health/Resources/Info.plist
----
**주의⚠️:** 해당 PR이 병합된 후, 반드시 프로젝트의 최상위 디렉토리에 
`app-debug.xconfig`와 `app-release.xcconfig` 파일을 추가하셔야 빌드가 제대로 됩니다. 
(.xcconfig 파일은 gitignore되어 있습니다.)
----
- `.xcconfig` 파일로부터 `Client_id` 값을 제대로 불러오지 못하는 문제 수정
---
| 1  | 2   |
| :-:| :-: |
|  <img width="355" height="101" alt="스크린샷 2025-08-07 오후 3 49 22" src="https://github.com/user-attachments/assets/60601fe7-bf38-478a-aa65-e4d0aa627ced" /> |     |
---
- .xcconfig 파일은 오늘자 회의록에 첨부해두었습니다. 자신 클라이언트 키로 수정 후, 사용하세요~
- **중요⭐️:** 각 `xcconfig` 파일에 번들 ID를 입력받을 수 있는 입력란이 있습니다. 각자 개발 환경에서 번들 ID를 수정하셔서 **본인의 번들 ID를 사용**해주세요. HealthKit Entitlements 문제도 사라지리라 생각됩니다.
> feat: info.plist에 Client ID 키 추가, 빌드 스킴에 따라 xcconfig를 받도록 수정, xcconfig에 따라 서로 다른 번들 ID로 세팅되도록 빌드 설정 수정

- Health/Presentation/Chatbot/Chatbot.storyboard
- Health/Presentation/Chatbot/ChatbotViewController.swift
- Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleCell.swift
> ex) closed 이슈넘버 #61 : 키보드 dismiss 시 스크롤 안되어서 마지막 메시지 가려지는 것 수정
- 키보드가 present로 유지될 때 타이핑해서 스크롤 발생시 가려졌던 부분도 해결
- 키보드 dismiss, present 되었을 때 가려짐 현상, 키보드 높이 상태값 업데이트 반영해 적용
---
- 키보드 인셋 계산, notification willShow, willHide로 분리한 것을 Notification 하나에서 처리해 그 안에서 키보드 프레임의 현재 높이값 계산해 scroll되게 함
- MainActor로 선언 concurrency로 최대한 변경
- 필요한 부분 DocC 주석 달기
- deinit 대신 viewDidDisappear에서 Task 취소 수행해 Swift6 경고 메시지 제거
- 키보드 작업할 때, 네트워크 연결 여부 코드 삭제해버림. 차후 커밋 후 이 PR 내에서 추가 예정
---
- 본인의 bundle id 설정, api key설정하여 테스트 하시면 됩니다.
- 디버그 모드, 릴리즈 모드 둘다 확인해보시고, 시뮬레이터와 실기기에서도 확인 부탁드려요
---
- 기승님의 navigationBar 제약이 컬렉션뷰와 타이틀에 걸려서 뭔가 버튼 인터랙션이 원할하지 않음. 이건 차후 기승님과 해결 예정
- 네트워크 연결 토스터블 코드 지워버렸는데 나중에 별도 PR에서 추가하겠습니다.
---
| 1  릴리즈 화면 | 2 디버그 화면(키보드 올라왔을때 모습)   |
| :-:| :-: |
|  <img width="300" …
> feat/chatbot response: 동적 테이블뷰 내에서 컨텐츠가 가려지지 않도록 키보드 인터랙션 처리 및 Swift Concurrency로 코드 변경

- Health/Application/AppDelegate.swift
- Health/Application/SceneDelegate.swift
- Health/Core/DIContainer/DIContainer+Register.swift
- Health/Core/DIContainer/InjectIdentifier+Keys.swift
- Health/ViewModels/EntityViewModels/DailyStepViewModel.swift
- Health/ViewModels/EntityViewModels/GoalStepCountViewModel.swift
- Health/ViewModels/StepSyncViewModel.swift
- 앱이 포그라운드 상태가 될 때마다 걸음 데이터를 동기화하는 로직을 추가했습니다.
- 동기화 로직에서는 2가지 작업을 진행합니다.
- 이전 날짜에 기록이 없으면 채우기
- 현재 걸음수 업데이트하기
- 온보딩 후 동기화
날짜 | 사용자의 행동 | GoalStepCount 엔티티 상태 | 생성된 DailyStep 및 스냅샷
-- | -- | -- | --
8/1 | 앱 최초 실행 (온보딩) → 목표 10,000보 설정 | ✅ GoalStepCount(effectiveDate: 8/1, goalStepCount: 10000) | ✅ DailyStep(date: 8/1, stepCount: 0, goalStepSnapshot: 10000) (stepCount의 초기값은 HealthKit으로 덮어써야 함)
| <strong>8/2</strong> | 앱 미접속 | 변경 없음 | ❌ 없음
| <strong>8/3</strong> | 앱 진입 → HealthKit로 8/3 걸음 수 8,000보 확인 | 변경 없음 | ✅ 8/2: <code>DailyStep(stepCount: 4000, goalStepSnapshot: 10000)</code></br>✅ 8/3: <code>DailyStep(stepCount: 8000, goalStepSnapshot: 10000)</code> |  
<strong>8/4~8/9</strong> | 앱 미접속 | 변경 없음 | ❌ 없음 |
| <strong>8/10</strong> | 앱 진입 → 목표를 5,000보로 변경 | ✅ …
> feat: 앱 실행시 걸음 데이터 동기화 로직 추가

- Health/Core/Views/StatusProgressBarView/StatusProgressBarView.swift
[Notion Task](https://www.notion.so/oreumi/StatusProgressView-UI-24aebaa8982b809f8af1c02ce0ee89ee?source=copy_link)
- 연령대 별로 보행 보폭, 속도 및 이중 지지 시간이 적절한지 시각적으로 보여주기 위해 `StatusProgressBarView` UI 코드 작성하였습나다.
- 한 가지 문제 아닌 문제라면.. 모든 색상 및 x축 레이블은 동일한 간격만을 가집니다. x축 값은 [3, 6, 9, 12]로만 가질 수 있으며, [1, 5, 8, 44]로는 가질 수 없습니다. 
---
| 1  | 2   |
| :-:| :-: |
| <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-10 at 13 19 31" src="https://github.com/user-attachments/assets/0a521c0f-f12a-4729-9409-fb14416af47a" />   |   <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-10 at 13 18 59" src="https://github.com/user-attachments/assets/a8c51a81-b2d6-4580-a516-942156502d61" />  |
| <img width="1206" height="2622" alt="Simulator Screenshot - …
> feat: `StatusProgressBarView` UI 코드 작성

- Health.xcodeproj/project.pbxproj
- Health/Core/Utils/Extensions/Date+Extension.swift
- Health/Presentation/Chatbot/ChatbotViewController.swift
- Health/Services/HealthService/DefaultHealthService.swift
- Health/Services/HealthService/MockHealthService.swift
- Health/Services/HealthService/Protocol/HealthService.swift
- Health/Services/NetworkService/Protocol/NetworkService.swift
[Notion Task](https://www.notion.so/oreumi/HealthKitService-24bebaa8982b8011bccae23e58e96861?source=copy_link)
- `HealthService`에서 읽기 권한 여부를 확인하는 메서드를 추가로 구현하였습니다. (checkHasAnyReadPermission() 메서드)
- ChatBotViewController와 AlanViewModel에서 발생하는 Swift Concurrency 경고를 제거하였습니다 (완벽하게 해결한 건 아님)
@haejaejoon 
@kwondohyun12 
- HealthService에 새롭게 추가된 메서드 꼭 확인해주세요~ 감사합니다.
> feat: HealthKitService에 읽기 권한 여부를 확인하는 메서드 추가 구현

- Health/Core/Views/CircleProgressView/CircleProgressView.swift
- Health/Core/Views/StatusProgressBarView/StatusProgressBarView.swift
- Health/Presentation/Dashboard/Content/Enum/DashboardCardType.swift
- Health/Presentation/Dashboard/Content/Enum/DashboardStackType.swift
- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/ViewModels/Cells/DailyGoalRingCellViewModel.swift
- Health/ViewModels/Cells/HealthInfoCardCellViewModel.swift
- Health/ViewModels/Cells/HealthInfoStackCellViewModel.swift
[Notion Task](https://www.notion.so/HealthInfoCard-DailyGoalRing-UI-24cebaa8982b8028bc22df1294951a6d?source=copy_link)
- `StatusProgressBarView`에서 현재 값으로 `nil`을 전달하면 Dot Indicator가 사라지지 않는 문제를 수정하였습니다.
- `CircleProgressView`에서 현재 값으로 `nil`을 전달하면 예외 UI (-)가 뜨도록 로직을 수정하였습니다.
- `DailyGoalRing`, `HealthInfoStack` 및 `HealthInfoCard` 셀에 실제 HealthKit 데이터를 주입 및 HealthKit 데이터 불러오기 실패 시, 예외 UI가 뜨도록 구현하였습니다.
---
- 건강 데이터 불러오기 실패 시, 단순히 대시(-) 처리를 하고 있습니다. 추후 더 좋은 방안 강구해보겠습니다.
- 다음 작업으로 `Bar Charts`와 `AI 요약` 셀에 실제 데이터를 주입 · 예외 처리 작업을 할 예정입니다.
- 현재 각 셀에서 HealthKit에 접근해 데이터를 가져오고 있는데, `DashboardViewModel`에서 한꺼번에 건강 데이터를 모두 가져온 뒤 셀에 뿌리는 식으로 개선할 예정입니다.
---
| 1  | 2   |
| :-:| :-: |
|  ![IMG_170B9156BC46-1](https://github.com/user-attachments/assets/f75a2b66-0ead-4527-b992-9883ef2df07f)  |   <img …
> feat: `DailyGoalRing`, `HealthInfoStack` 및 `HealthInfoCard` 셀에 실제 HealthKit 데이터를 주입 및 건강 데이터 불러오기 실패 시, 예외 UI가 뜨도록 구현

- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Managers/CalendarLayoutManager.swift
- Health/Presentation/Calendar/Managers/CalendarScrollManager.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- Health/ViewModels/CalendarViewModel.swift
- 달력의 레이아웃을 생성하는 로직은 CalendarLayoutManager로
스크롤 관련 로직은 CalendarScrollManager 로 분리했습니다.
- 데이터 변경 감지 콜백 (`onDataChanged`) 을 AsyncStream 으로 교체했습니다.
- [노션 태스크](https://www.notion.so/oreumi/Calendar-LayoutManager-ScrollManager-24debaa8982b80d5935fefaea9f2651c?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> refactor: Calendar 코드 책임 분리를 위한 LayoutManager, ScrollManager 추가

- Health/Presentation/Calendar/Calendar.storyboard
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Managers/CalendarLayoutManager.swift
- Health/Presentation/Calendar/Managers/CalendarScrollManager.swift
- 아이패드 가로모드에서는 캘린더 탭 달력을 3열로 적용합니다.
- 경고 메시지 처리를 위해 Calendar.storyboard 의 CollectionView Cell 을 제거합니다.
- 아이패드 회전시 스크롤 위치가 이상한 문제가 있어서, 이전에 보고 있던 월이 상단에 위치하도록 합니다.
| 아이패드 세로 | 아이패드 가로 |
| -- | -- |
| <img width="2064" height="2752" alt="simulator_screenshot_8C7348BD-87D0-4A60-B371-D3255C1E3363" src="https://github.com/user-attachments/assets/cf8f4c2a-1b2f-4358-9287-c1d9c2b8e511" /> | <img width="2752" height="2064" alt="simulator_screenshot_9AFDCF19-686E-424E-89E3-FB81696EE990" src="https://github.com/user-attachments/assets/4b0bdb3f-50a5-4f45-a9d6-fdcdebf462f9" /> |
- [노션 태스크](https://www.notion.so/oreumi/3-24debaa8982b80a280a2e070624c612a?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> chore: 캘린더 탭 달력을 아이패드 가로에서는 3열로 적용, 회전시 스크롤 위치 보정

- Health/Presentation/Calendar/Views/CalendarMonthCell.xib
- CalendarMonthCell 의 CollectionView 높이 제약에서 충돌 발생
→ 스토리보드에서 우선순위를 999로 수정하여 경고 메시지 대부분 제거
- [노션 태스크](https://www.notion.so/oreumi/24debaa8982b8032b2a1e99130b10bb9?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> fix: 캘린더 관련 제약조건 충돌로 인한 콘솔 경고 메시지 제거

- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Managers/CalendarScrollManager.swift
- 아이패드에서 상태바(Status Bar) 영역을 탭하면 최상단으로 스크롤됩니다. (Scroll to Top)
- 이때 무한스크롤이 중복으로 동작하는 문제를 수정했습니다.
- [노션 태스크](https://www.notion.so/oreumi/Scroll-to-Top-24debaa8982b80cbb6c5ead8d237aec5?source=copy_link)
> fix: 아이패드 캘린더 Scroll to Top 시 무한스크롤 중복 동작 문제 수정

- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
- Health/Services/HealthService/MockHealthService.swift
- Health/ViewModels/Cells/HealthInfoStackCellViewModel.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
- Health/ViewModels/Dashboard/Enum/LoadState.swift
[Notion Task](https://www.notion.so/oreumi/UI-24eebaa8982b80bc8efae3605a414273?source=copy_link)
---
- `LoadState`가 (권한 없음을 의미하는) `denied`도 가지도록 코드를 수정하였습니다.
- `DashboardViewModel`에서 각 셀의 뷰-모델에 `denied` 상태도 전달하도록 코드를 개선하였습니다. (`데이터 가져오기 실패`와 `권한 없음` 상태를 보다 엄격히 구분)
- 아이패드 환경에서 `걸은 거리` 셀 옆에 라인 차트가 그려지지 않는 문제를 수정하였습니다.
- 대시보드 상단의 `걸은 거리`, `운동 시간` 셀의 심볼 원형 배경 색상을 `systemGray5`로 수정하였습니다. (`systemGray6`는 라이트 모드에서 안보임)
- 대시보드 중간의 `막대 그래프`에 borderWidth가 제대로 적용되지 않는 문제를 수정하였습니다.
---
- 이번 PR도 마찬가지로, PR이 너무 커질 것이 우려되어 한번 끊고자 올리게 되었습니다. 
- **다음 PR부터 (내일부터) `막대 그래프`, `보행 속도`, `보행 보폭` 셀에 대하여 예외 UI를 하나씩 구현할 계획입니다.** @giseungNoh 
---
| 1  | 2   |
| :-:| :-: |
|  <img width="1179" height="2556" alt="IMG_0448" src="https://github.com/user-attachments/assets/afdd0a98-ac7a-4f69-a676-d438be360c19" />  |  <img …
> feat: `DahsboardViewModel`에서 `denied` 상태도 방출, 대시보드의 일부 셀의 UI 색상 및 제약 수정, 라인 차트가 그려지지 않는 문제 수정

- Health/Core/Storage/UserDefaults/UserDefaultsKeys.swift
- Health/Presentation/Profile/ProfileViewController.swift
- 설정에서 건강앱에서 데이터를 불러오는것에 대한 권한 
---
- 
---
- 
---
---
- 권한 변경을 위해 건강앱으로 연결해줍니다.
- Foreground 진입마다 권한을 확인해서 Switch를 설정하고 UserDefaults에 저장합니다.
- 권한이 하나라도 있을시 On, 하나도 없을시 Off
> feat: Profile 건강 데이터 권한 핸들링

- Health/Core/Views/PermissionDeniedView/PermissionDeniedCompactView.swift
- Health/Core/Views/PermissionDeniedView/PermissionDeniedFullView.swift
- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
- Health/ViewModels/Dashboard/DashboardViewModel.swift
---
- 대시보드의 각 셀에서 해당하는 건강 데이터에 접근할 수 없으면 `권한 없음` UI를 띄우도록 코드를 작성하였습니다. (앨런 AI 요약 셀 제외)
- 대시보드의 각 셀에서 그림자 불투명도를 살짝 높여 입체감을 주었습니다.
---
- 설정 화면에서 권한 설정을 바꾸고, 다시 앱에 진입한다 하더라도 데이터가 갱신되지 않습니다. 앱을 완전히 종료 후 다시 여셔야 바뀐 권한에 맞게 데이터가 갱신됩니다.
---
- 아침에 구현한 `PermissionDeniedView`를 조금 더 범용적으로 사용할 수 있도록 개선이 필요해보입니다. (예: 데이터 불충분 예외)
---
| 1  | 2   |
| :-:| :-: |
|  <img width="1179" height="2556" alt="IMG_0453" src="https://github.com/user-attachments/assets/07708e35-579c-4564-a4a3-f8d77a936074" />  |  <img width="1179" height="2556" alt="IMG_0454" src="https://github.com/user-attachments/assets/f228f337-041a-4ee8-b3ca-0129a9bbd28e" />   |
| <img width="1179" height="2556" alt="IMG_0455" src="https://github.com/user-attachments/assets/d1893ff2-85b1-4efc-82cc-6fa6600 …
> feat: 대시보드의 각 셀에서 `접근 권한 없음` 뷰를 띄우도록 코드 작성

- Health/Core/DIContainer/DIContainer+Register.swift
- Health/Core/DIContainer/InjectIdentifier+Keys.swift
- Health/Core/Indicators/ActivityIndicator/AlanLoadingIndicatorView.swift
- Health/Core/Indicators/ActivityIndicator/CustomActivityIndicatorView.swift
- Health/Core/Storage/CoreData/CoreDataStack+Dummy.swift
- Health/Core/Storage/CoreData/CoreDataStack.swift
- Health/Core/Views/CircleProgressView/CircleProgressView.swift
- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/Resources/Assets.xcassets/appOffWhite.colorset/Contents.json
- Health/Services/CoreDataSerice/DefaultCoreDataUserService.swift
- Health/Services/CoreDataSerice/Protocol/CoreDataUserService.swift
- Health/Services/HealthService/MockHealthService.swift
- Health/Services/HealthService/Protocol/HealthService.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
[Notion Task]()
---
- `MockHealthService`가 전달되는 건강 데이터 타입에 따라 알맞은 값을 반환하도록 코드를 개선하였습니다.
- `원형 프로그래스 바`의 선 두께, 그라디언트 색상을 변경하였습니다. (라이트 모드에서도 그라디언트가 적용되도록)
- 대시보드의 각 셀에서 `BorderWith` 값을 1에서 0.75로 조정하였습니다.
- `CoreDataUserService` 서비스 객체 생성 및 DIContainer에 주입하였습니다. (뷰-모델이 SwiftUI로 작성되어 있어서.. 수정하기도 그래서 하나 작성했어요) **`수정 #1`**
- 대시보드 및 분석 화면에서 사용할 `AlanLoadingIndicatorView` UI를 작성했습니다.  **`수정 #2`**
| | |
| :--: | :--: |
| <img width="349" height="59" alt="스크린샷 2025-08-15 오전 12 48 01" src="https://github.com/user-attachments/assets/5f59d209-6e78-454d-b41a-14b59fa441c1" /> | <img width="350" height="62" alt="스크린샷 2025-08-15 오전 12 47 51" src="https://github.com/user-attachments/assets/da1bccb8-881e-407c-8cd5-85b0fd53e00f" /> |
| <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 …
> feat: `원형 프로그래스 바`의 선 두께 및 색상 변경, `MockHealthService`가 실제 유용한 값을 반환하도록 개선 (수정 #2)

- Health/Application/SceneDelegate.swift
- Health/Core/DIContainer/DIContainer+Register.swift
- Health/Core/DIContainer/InjectIdentifier+Keys.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- Health/Services/CalendarStepService/CalendarStepService.swift
- `CoreData Entity`로부터 `DefaultCalendarStepService`를 통해 걸음 수 데이터를 달력으로 가져옵니다. (현재는 더미로 테스트)
- 기존에 있는 `DailyStepViewModel`/`GoalStepCountViewModel` 을 경유해서 걸음 수 데이터를 가져오면 초기화 타이밍이 맞지 않아서 CoreData를 직접 조회하도록 합니다.
DEBUG 환경에서 일주일간 생성된 CoreData 더미 엔티티가 보이는지 확인
- [노션 태스크](https://www.notion.so/oreumi/CoreData-CalendarStepService-24eebaa8982b8033a80bd3df1dd81c52?source=copy_link)
> feat: CoreData로부터 달력에 걸음 수 데이터를 제공하는 CalendarStepService 추가

- Health/Core/DIContainer/DIContainer+Register.swift
- Health/Core/DIContainer/InjectIdentifier+Keys.swift
- Health/Core/Privacy/AddressRegionClassifier.swift
- Health/Core/Utils/Concurrency/NCObserverBox.swift
- Health/Presentation/Chatbot/Chatbot.storyboard
- Health/Presentation/Chatbot/ChatbotViewController.swift
- Health/Presentation/Chatbot/Content/ChatbotContent.swift
- Health/Presentation/Chatbot/Views/Cells/AIResponseCell.swift
- Health/Presentation/Chatbot/Views/Cells/AIResponseCell.xib
- Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleView.swift
- Health/Presentation/Chatbot/Views/Cells/LoadingResponseCell.swift
- Health/Services/NetworkService/AlanSSEClient.swift
- Health/Services/NetworkService/SSEService/AlanSSEClient.swift
- Health/Services/NetworkService/SSEService/AlanSSEParser.swift
- Health/Services/NetworkService/SSEService/AlanSSEService.swift
- Health/Services/NetworkService/SSEService/Protocol/AlanSSEClientProtocol.swift
- Health/Services/NetworkService/SSEService/Protocol/AlanSSEServiceProtocol.swift
- Health/ViewModels/AlanViewModel.swift
- Health/ViewModels/ChatbotViewModel.swift
> ex) close #121 응답값 끝에 잘리는 이슈 해결 
https://github.com/rlarjsdn3/EST-Soft-Team3-3rd-Project/pull/121#pullrequestreview-3126595303
---
-  문제
- AIResponseCell에서 여러 줄 텍스트를 표시할 때 마지막 줄이 잘리거나 셀 높이가 맞지 않는 문제가 발생함.
- 특히 회전, 다이내믹 타입, 스트리밍 입력(typewriter effect) 상황에서 재현됨.
-  원인
-  UITableView의 automatic dimension이 UITextView의 최신 contentSize를 반영하지 못하는 경우가 있었음
-  UITextView 기본 동작(`allowsNonContiguousLayout = true`)으로 인해 줄바꿈 시 부분 레이아웃만 업데이트되어 잘림 발생
-  텍스트 변경 직후 셀 전체(contentView) 레이아웃이 확정되지 않은 상태에서 높이 계산이 이루어짐
-  해결
-  responseTextView에 allowsNonContiguousLayout = false 설정 → 줄바꿈 시 레이아웃 안정화
-  systemLayoutSizeFitting 오버라이드 → sizeThatFits 기반으로 정확한 높이 반환, 항상 올바른 셀 높이 반영
-  텍스트 갱신 시 contentView.layoutIfNeeded()를 호출한 뒤 onContentGrew 실행 → 테이블뷰 높이 계산과 레이아웃 사이클 동기화
Chatbot 관련 구조 
```bash
├── ViewModels
│ …
```
> feat/chatbot : 응답값 잘림 이슈 및 SSE 서비스 코드 추가, DIContainer 등록, 네트워크 연결 모니터 설정(리팩토링) 

- .github/workflows/ci.yml
- 고장난 GitHub Action을 고쳤어요.
> 깃허브 액션 상에서는 Xcode 16.4 버전과 iOS 18.4를 기준으로 빌드 및 테스트를 수행합니다. 가급적 Xcode 16.4 버전 이상으로 업데이트해주실 것을 권장드립니다~
> fix: 고장난 GitHub Action 수리, Xcode 버전을 `16.1`에서 `16.4`로 업데이트

- Health/Resources/Assets.xcassets/Toastable-warning/Contents.json
- Health/Resources/Assets.xcassets/Toastable-warning/toastStrokeColor.colorset/Contents.json
- Health/Resources/Assets.xcassets/Toastable-warning/toastSubTitleColor.colorset/Contents.json
- Health/Resources/Assets.xcassets/Toastable-warning/toastWarningBgColor.colorset/Contents.json
- Health/Resources/Assets.xcassets/Toastable-warning/warningSymbolColor.colorset/Contents.json
---
-  토스트 메시지 배경색
- 토스트 메시지 스트로크
- 토스트 메시지 심볼색
- 토스트 메시지 subtitle 색(dark `#d7d7d7`로 변경)
- 토스트메시지 title 색은 `.label`(white, black) 그냥 쓰심 됩니다.
- alpha값은 1.0 으로 맞춰주시면 됩니다.
-
> design: toastable warning - 경고 토스트 메시지 컬러에셋 추가

- Health/Core/ViewControllers/HealthTabBarController.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Managers/CalendarScrollManager.swift
- 3가지 문제점을 수정했습니다.
1. 캘린더 탭이 disappear 되고나서 다시 돌아왔을 때 무한스크롤이 동작하지 않는 문제
2. 달력의 날짜를 탭해서 열리는 대시보드창을 닫았을 때 현재 월로 스크롤이 초기화되는 문제
3. 현재 월로 스크롤시키는 버튼이 간혹 현재 월이 화면에 보이더라도 숨겨지지 않는 문제
- [노션 태스크](https://www.notion.so/oreumi/254ebaa8982b8032ab1be9c37c49337e?source=copy_link)
> fix: 캘린더 탭에서 무한스크롤이 제대로 동작하지 않는 문제 수정

- Health/Presentation/Profile/BodyInfoViewController.swift
- 신체 정보에서 Title 아래에 있던 DetailText를 우측으로 옮겼습니다.
---
-
-
> refactor: detailLabel 셀의 우측으로 수정, 컬러변경

- Health/Presentation/Calendar/Views/CalendarDateCell.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- 달력에서 현재 걸음 수와 목표 걸음 수 데이터가 있는 날짜만 클릭이 가능하도록 수정했습니다.
- CalendarDateCell.swift의 private method들은 `extension`으로 분리했습니다.
- [노션 태스크](https://www.notion.so/oreumi/254ebaa8982b80b59f5dd25071dd996b?source=copy_link)
> feat: 캘린더 탭 달력의 날짜 중 유효한 걸음 수 데이터가 있는 셀만 클릭이 가능하도록 수정

- Health/Presentation/Calendar/Managers/CalendarLayoutManager.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.xib
- 캘린더 탭 월 레이블 (예: 2025년 8월) 을 맞춤케어 탭의 소제목과 동일하게 적용합니다.
- 폰트 사이즈 및 색상, 수직 여백 수정
| Before | After |
| -- | -- |
| <img width="342" height="371" alt="image" src="https://github.com/user-attachments/assets/e6112f92-325d-417b-816e-19cfbf37188d" /> | <img width="344" height="364" alt="image" src="https://github.com/user-attachments/assets/beca4fdf-56fd-4a21-8746-adc1c748775c" /> |
- [노션 태스크](https://www.notion.so/oreumi/255ebaa8982b806192bffb70f9b2e68d?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> chore: 캘린더 탭의 월 레이블을 맞춤케어 탭의 소제목과 동일하게 적용

- Health/Presentation/Dashboard/Content/DashboardContent.swift
- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/ViewModels/Cells/DashboardBarChartsCellViewModel.swift
- Health/ViewModels/Cells/DashboardTopBarViewModel.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
[Notion Task](https://www.notion.so/oreumi/Pull-to-Refresh-254ebaa8982b80dfabd9fefb076132b8?source=copy_link)
- `DashboardTopBarViewModel` 코드 작성 및 Pull-to-Refresh 시, 기준 시각이 제대로 갱신되지 않는 문제를 수정하였습니다.
- 대시보드 하단의 `보행 밸런스 분석` 셀에서 숫자 포매팅을 더욱 정교하게 처리하도록 코드를 개선하였습니다.
---
| 1  |
| :-:| 
|   <img width="1179" height="2556" alt="IMG_0489" src="https://github.com/user-attachments/assets/a9b9678a-129d-4287-b5c4-1dd062182b76" /> |    
* 기존에는 `1`, `1.2`, `1.4`...  로 표시되었는데, `1.0`, `1.2`, `1.4`... 로 표시되게 개선하였습니다.
---
> feat: `DashboardTopBarViewModel` 코드작성 및 Pull-to-Referesh 시, 기준 시각이 제대로 갱신되지 않는 문제 수정

- Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Dashboard/Dashboard.storyboard
- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/AISummaryLabel.swift
- Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
[Notion Task](https://www.notion.so/oreumi/HealthNavigationBar-255ebaa8982b805dbd66d37f806489cc?source=copy_link)
---
- 대시보드에 `HealthNavigationBar` 코드를 적용하였습니다. 대시보드와 달력 모두 **스크롤을 해야지** 네비게이션 타이틀이 표시됩니다.
1. 이는 의도된 구현입니다. 대시보드 화면은 이미 라지 타이틀(largeTitle)이 존재하기 때문에, 라지 타이틀과 네비게이션 타이틀이 모두 표시되면 굉장히 어색해 보이기 때문입니다.
2. 이러한 구현은 다른 화면에서는 적용할 필요는 없어 보입니다.
- `HealthNavigationBar`에 타이틀을 숨길 수 있는 속성을 추가하였습니다. `isTitleLabelHidden`
- 대시보드 셀의 스트로크 색상을 `boxBgLightModeStroke`으로 수정하였습니다. 
---
| 1  | 2   |
| :-:| :-: |
|  <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-20 at 14 15 07" src="https://github.com/user-attachments/assets/5f81783c-9f53-4fa5-ad45-4578bec13c25" />  |   <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-20 at 14 14 54" …
> feat: 대시보드에 `HealthNavigationBar` 코드 적용 및 캘린더로부터 대시보드에 진입하면 AI 요약을 하지 않도록 코드 수정

- Health/Presentation/Calendar/Views/CalendarDateCell.swift
- 캘린더 탭 달력 날짜셀에는 라이트모드에서만 보이는 테두리가 있습니다.
- 데이터가 없는 셀인지 현재 걸음 수가 0인 셀인지 구분할 수 없는 상태입니다.
- 따라서, 데이터가 없는 셀(= 클릭이 불가능한 셀)은 테두리를 제거했습니다.
| Before | After |
| -- | -- |
| <img width="340" height="359" alt="image" src="https://github.com/user-attachments/assets/0a24df01-ef6b-4764-b24f-858c2c8cc743" /> | <img width="337" height="357" alt="image" src="https://github.com/user-attachments/assets/d166a0e1-c1fa-4afe-8b76-5a1d78823223" /> |
- [노션 태스크](https://www.notion.so/oreumi/255ebaa8982b8043bdbfc8db829c8ba6?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> chore: 캘린더 탭 달력에 데이터가 없는 날짜셀은 테두리 제거

- Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift
- Health/Presentation/Base.lproj/Main.storyboard
- Health/Presentation/Calendar/Calendar.storyboard
- Health/Presentation/Calendar/CalendarViewController.swift
- CalendarViewController에 HealthNavigationController 를 상속받았습니다.
- 네비게이션 바가 올바른 위치에 있게 하기 위해 스토리보드 제약을 일부 수정했습니다.
- 우측 하단에 있던 현재 월로 스크롤하는 버튼을 네비게이션 바 아이템으로 옮겼습니다.
| 아이폰 | 아이패드 |
| -- | -- |
| <img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/c1be1747-1004-4b0f-8c8e-42d17f12d181" /> | <img width="1640" height="2360" alt="image" src="https://github.com/user-attachments/assets/5c657d28-9c75-4b08-9330-14d5683a1041" /> |
- [노션 태스크](https://www.notion.so/oreumi/HealthNavigationController-256ebaa8982b80cb89a6c5a46a5bd142?source=copy_link)
> feat: 캘린더 탭에 HealthNavigationController 적용 및 현재 월로 스크롤하는 버튼을 네비게이션 바로 이동

- Health/Presentation/Onboarding/MainVC/HeightViewController.swift
- Health/Presentation/Onboarding/MainVC/WeightViewController.swift
---
- 사용자가 몸무게, 신장 입력시 000, 090, 012 이런식으로 입력해도 넘어가지는 문제확인후 수정 
- 사용자가 신장 입력시 사용자가 올바른값을 입력했을때만 accentColor적용되게 다시 수정
---
- 
---
- 
---
https://github.com/user-attachments/assets/29216467-541f-467a-ad30-17faa123e850
영상엔 에러메세지가 나오는데, pr버전에선 안나오게 만들어놧습니다. 
---
-
> feat: 몸무게뷰,신장뷰 로직 수정

- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
- 대시보드 보행 밸런스 설명 시트 UI를 개선했어요.
- 대시보드에서 실제 목표 걸음 수 데이터를 가져와 화면에 출력하도록 코드를 작성했어요. 
---
- 다음 PR에 할 일: 프로필 화면에서 목표 걸음 수 갱신 시, 대시보드 다시 로드하도록 하기
---
| 1  | 2   |
| :-:| :-: |
|  <img width="1640" height="2360" alt="Simulator Screenshot - iPad Air 11-inch (M3) - 2025-08-22 at 10 04 28" src="https://github.com/user-attachments/assets/449e801f-2f80-47b5-939a-bdef3e8dfff7" />  |  <img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-22 at 10 03 45" src="https://github.com/user-attachments/assets/b8ea8f1f-be8f-46a5-91df-d3c95e77049e" />
|
---
> feat: 대시보드 보행 밸런스 설명 시트 UI 개선, 실제 목표 걸음 수 데이터를 가져오도록 코드 수정

- Health/Presentation/Onboarding/MainVC/DiseaseViewController.swift
- Health/Presentation/Onboarding/MainVC/GenderSelectViewController.swift
- Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
- Health/Presentation/Onboarding/MainVC/HeightViewController.swift
- Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift
- Health/Presentation/Onboarding/MainVC/OnboardingViewController.swift
- Health/Presentation/Onboarding/MainVC/StepGoalViewController.swift
- Health/Presentation/Onboarding/MainVC/WeightViewController.swift
---
- continue버튼 하이라이트 추가 (기존 볼드처리로직 제거하고, 볼드인상태에서 하이라이트적용)
- **중요 변동사항 ⭐️⭐️⭐️**
기존 연동 로직
- 사용자에게 설정앱으로 이동하는 경고창을띄워 강제적으로 설정앱으로 이동하게만들어서
사용자에게 무조건 권한을 설정해야된다의 느낌의 로직
- 연동안하고 넘어갈때, 사용자에게 연동설정에관한 알람창을 띄웠었음 
수정후 
- 사용자에게 권한설정알람을 띄워줬을때, 알람창 하단에 선택하는 분기 설정 
앱 작동이 정상적으로안될수도있습니다. 연동하실겁니까? 
취소(온보딩 계속 진행) / 설정으로 이동 
- 기존 다음 버튼을 눌렀을때, 사용자에게 다시 연동설정에 관한 알람창을 띄웠으나, 이제 스위치만 눌러도 사용자에게 물어보고 분기점을 
나눔으로서, 이부분은 개발자의 의도가 중복되므로 기존에 다음버튼눌렀을때 알람창띄우는 로직은 삭제
- 화면을 날리거나, 설정화면으로 이동했다가 다시 들어왔을때 스위치가 켜져있는것도확인. (연동성공시) 
- 설정앱이아닌, 바로 건강앱으로 갈수있게 일단은 구현, 이부분은 추후 논의사항에 의해 다시 설정앱이동으로 변동될가능성있어
이전코드는 주석처리 
---
- 꼭 실기기로 확인하셔야합니다. 시뮬레이터상으론 스위치가 살아있는지 죽어있는지 연동이안되서 확인불가능이에요 
---
- 
---
---
-
> feat: 버튼 하이라이트추가 + 헬스킷 로직 변경 (PR설명 참고)

- Health/Core/CoreGradientViewController.swift
- Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- Health/Presentation/Onboarding/MainVC/StepGoalViewController.swift
- 캘린더 탭 달력에 "걸음" 연동 상태에 따라 데이터 표시 여부를 결정하도록 했습니다.
- 일부 불필요하다고 생각되는 `print()` 를 제거했습니다.
- [노션 태스크](https://www.notion.so/oreumi/258ebaa8982b80bbb736d6e858da78d6?source=copy_link)
> fix: 건강 앱 연동을 해제해도 캘린더 탭 달력에 데이터가 표시되는 문제 수정

- Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.swift
- Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.xib
- Health/Services/CourseService/WalkingCourseService.swift
---
- 코스 경로는 라이트 모드로 고정 시켰습니다
-> 라이트모드, 다크모드일때 즉각적으로 바뀌기 위해서는 결국 라이트 모드일때와 다크모드일때의 지도 스냅샷을 두번 만들어야해서 비효율적이고 이미지 생성되는게 너무 느려서 라이트모드로 고정시켰습니다.
-난이도가 쉬움이면 노랑색, 보통이면 주황색, 어려움이면 빨간색으로 표시됩니다.
-GPX 좌표값 캐싱 추가
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
> fix:코스 경로 라이트모드로 고정 및 좌표값 캐싱 추가

- HealthTests/ViewModels/CalendarViewModelTests.swift
- CalendarViewModel에 대한 테스트 코드를 추가했습니다.
| DEBUG - 아이폰 | DEBUG - 아이패드 |
| -- | -- |
| <img width="530" height="199" alt="image" src="https://github.com/user-attachments/assets/0b66299d-0bf8-4585-b4f1-7bd7885be4d2" /> | <img width="533" height="199" alt="image" src="https://github.com/user-attachments/assets/8557ddfe-ee3e-47cc-a66b-ed8734ddb7c2" /> |
- [노션 태스크](https://www.notion.so/oreumi/CalendarViewModel-25bebaa8982b809ca731dd4e23968182?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
> test: CalendarViewModel 테스트 코드 추가

- Health/Core/Utils/Notification+Name.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Profile/ProfileViewController.swift
프로필 탭에서 건강 앱 연동을 끄는 경우, 캘린더 탭 달력에도 즉시 반영하도록 합니다.
> fix: 프로필 탭에서 건강 앱 연동 해제시, 캘린더 탭 달력 데이터 숨기기

- Health.xcodeproj/project.pbxproj
- Health/Core/Protocols/ToastType.swift
- Health/Core/Protocols/Toastable.swift
- Health/Core/Shared/SharedStore.swift
- Health/Presentation/Chatbot/Chatbot.storyboard
- Health/Presentation/Chatbot/ChatbotViewController.swift
- Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleView.swift
- HealthWidget/Info.plist
---
- 아이폰에서 키보드에서 가려지던 챗봇 맞춤 토스터블 메시지 위치 수정
- 위젯 관련 빌드 세팅 수정 > info에 xcconfig 환경변수 Widget bundle identifie, app group identifier 설정 
- 챗봇 채팅창 UI 수정 > 기존에 라이트 모드에서 쉐도우 잘린건 Container safeArea 0으로 변경해 늘림, 상단 Container에도 8 여백 추가
---
- debug, release에서 혹은 아이패드에서 network 유실 복구시 뜨는 위치 확인 부탁드립니다.
- 채팅창 텍스트 필드 변경 사항 확인 부탁드립니다(다크모드, 라이트모드시 이상한 점 없는지)
---
- 
---
| 1 - 키보드 dismiss | 2 - 키보드 present   |
| :-:| :-: |
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/dc919858-7088-450d-9ac7-bb7be85a6f71" /> | <img width="300"  alt="image" src="https://github.com/user-attachments/assets/c6be5cef-d8d0-4143-b9e5-28ebde36b38e" /> |
|아이패드 때 상단 토스트|
|:--:|
| <img width="800" alt="image" …
> Feat/chatbot bug fix: 챗봇 맞춤 토스터블 메시지 위치 수정, 위젯 관련 빌드 세팅 수정, 챗봇 채팅창 UI 수정

- Health/Presentation/Personal/Views/SubView/CourseInfoView.swift
- 맞춤 케어 탭 코스 설명 시트 내 디자인을 가이드뷰와 동일하게 적용하였습니다.
| 가이드뷰 | 코스 설명 - Before | 코스 설명 - After |
| -- | -- | -- |
| <img width="1206" height="2622" alt="simulator_screenshot_EA95D51C-D561-40C0-A513-B4CD41D45DCC" src="https://github.com/user-attachments/assets/a10f5833-4314-4a9d-9c0a-b5aba4c1a709" /> | <img width="1206" height="2622" alt="simulator_screenshot_2F726443-075F-4C61-AB39-F19D45F32BCE" src="https://github.com/user-attachments/assets/93c76472-78c6-49d1-ad30-ce68dc4d8886" /> | <img width="1206" height="2622" alt="simulator_screenshot_869B9090-9447-4B84-86FC-2C5969D7518B" src="https://github.com/user-attachments/assets/dee370e7-505e-4860-8c76-c7c10e2b790f" /> |
> fix: 맞춤케어 탭 코스 설명의 디자인을 GuideView와 동기화

- Health/Core/Storage/UserDefaults/UserDefaultsKeys.swift
- Health/Presentation/Personal/PersonalViewController.swift
- Health/Presentation/Personal/Views/MainView/AISummaryCell.swift
- Health/Presentation/Profile/BodyInfoViewController.swift
- Health/ViewModels/Cells/MonthSummaryCellViewModel.swift
- Health/ViewModels/Cells/PersonalAlanSummaryCellViewModel.swift
- Health/ViewModels/Cells/WeekSummaryCellViewModel.swift
- Health/ViewModels/EntityViewModels/LLMRecommendationViewModel.swift
---
- 프로필에서 건강 권한 on, off에 따라 일주일, 한달 요약셀이 보이고 안보이도록 수정했습니다.
- 프로필화면에서 신체 정보 수정하면 CoreData에도 저장되도록 수정했습니다. @haejaejoon 
- 신체정보 수정해도 난이도가 잘 바뀌지 않는 버그 수정했습니다.
---
- 
---
- print문은 프롬프트 테스트 조금 더 해보고 정리 하겠습니다.
- 테스트 할때 프로필 탭에서 사용자 신체 정보 바꾸고 다시 맞춤 탭으로 돌아가서 난이도가 잘 바뀌는지 테스트 해주시면 감사하겠습니다.
---
| 1  | 2   |
| :-:| :-: |
https://github.com/user-attachments/assets/b7f749e3-32ad-4c76-94ba-a0cd94ad9c64
|    |     |
---
-
> fix: Personal- 프로필에서 스위치 on, off 하면 건강 권한 오류 화면도 연동되도록 수정 + 코스 난이도 제대로 불러오지 못하는 버그 해결

- Health/Presentation/Profile/Views/EditBirthdayView.swift
- Health/Presentation/Profile/Views/EditStepGoalView.swift
- 목표걸음 변경 단위 500으로 변경
- 태어난 해는 작년까지만 나오게 변경
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
> fix: 태어난해 Picker 현재년도 -1까지 나오게, 목표걸음 500씩으로 변경

- Health/Presentation/Calendar/Views/CalendarProgressBar.swift
캘린더 탭을 처음 열거나 포그라운드 상태로 진입할 때
달력의 프로그레스바가 순간적으로 가득 찼다가 줄어드는 의도되지 않은 애니메이션을 제거했습니다.
[노션 - QA](https://www.notion.so/oreumi/25cebaa8982b80c5b240c0045f75a176?v=242ebaa8982b8158aea0000cba0038c6&source=copy_link)
> fix: 캘린더 탭 달력 셀 프로그레스 바에 의도치 않은 애니메이션 발생하는 문제 수정

- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/Presentation/Profile/ProfileViewController.swift
@haejaejoon 
- 프로필 화면에서 건강 권한 스위치를 `on`으로 바꾸더라도 대시보드가 실시간으로 갱신되지 않는 문제를 수정했습니다.
- 대시보드의 상단 셀(걸은 거리, 운동 시간)의 값이 0.0222인 경우, 0.0으로 표시되는 문제를 수정했습니다. (이제는 0으로 표시) 
---
https://github.com/user-attachments/assets/5cb0cf24-f22c-46cd-96d3-0147305a88bf
> fix: 프로필에서 건강 스위치를 `on`하더라도 대시보드가 실시간으로 갱신되지 않는 문제 수정

- Health/Presentation/Onboarding/Delegates/CustomOnboardingNaviBarView.swift
- Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
- Health/Presentation/Onboarding/Onboarding.storyboard
>
---
온보딩뷰 사용 네비게이션바 여백 조정 
- 기존 horizontal alignment - left -> center로 변경
- vertical alignment center 추가 
- leading constraints 18 -> 12 조정
- button.heightAnchor 추가
다른뷰에서 보이는 경고창 매세지와 문구, 어투 통일완료 (healthLinkVC, stepGoalVC)
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
> feat: 경고창 message 문구 통일 작업 + 네비게이션바 백버튼 상하좌우 터치 대응 되도록 여백 수정

- Health/Core/Protocols/ScrollableToTop.swift
- Health/Core/Views/CircleProgressView/CircleProgressView.swift
- Health/Presentation/Dashboard/Content/Enum/DashboardStackKind.swift
- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
- Health/Presentation/Profile/ProfileViewController.swift
- Health/Services/HealthService/DefaultHealthService.swift
- Health/Services/HealthService/MockHealthService.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
> 변경사항이 조금 많습니다. 권한 상태에 따라서 값을 정확하게 잘 불러오는지 위주로 테스트하였습니다. 기타 자잘하게 눈엣가시도 해결했습니다.
- 헬스킷에서 `오른 층수`도 권한을 받도록 추가하였습니다.
- 대시보드에서 `운동 시간` 셀을 삭제 · `운동 시간` 셀을 삭제하였습니다.
> 이외 동작은 기존 데이터와 모두 동일합니다. 표시되는 데이터 유형만 달라졌습니다.
- 대시보드에서 권한 변경에 따라 실시간 리로드 로직을 개선하였습니다.
> 기존에는 `SceneDelegate` → `대시보드`로 곧바로 권한 변경 신호를 받았지만, 이제는 `SceneDelegate` → `프로필` → `대시보드`로 거치도록 개선하였습니다. 이는 유저 디폴츠의 `HealthKitLinked` 값이 확실히 변경된 다음, 대시보드에서 리로드를 하기 위함입니다.
@haejaejoon 
- 프로필 화면에 진입하면(viewDidLoad) 건강 데이터 권한 상태를 검사하는 로직을 추가하였습니다.
- 대시보드 하단 셀의 프로그래스 바의 dot이 정확한 지점에 위치하지 않을 수 있는 문제를 수정했습니다.
- 대시보드에서 액티비티 링에 이상한 실선이 생기는 문제를 해결했습니다. (이미지 참조)
---
- 앱을 완전히 종료한 뒤, 건강 데이터 권한을 바꾸고 다시 켜도 프로필 화면의 권한 스위치가 제대로 연동되는지 여부
| 1  | 2   |
| :-:| :-: |
|   <img width="1179" height="2556" alt="IMG_0541" …
> feat: 헬스킷에서 `오른 층수` 권한을 받도록 수정, 대시보드에서 운동 시간 대신 `오른 층수`가 표시되도록 수정

- Health/Core/Utils/Extensions/Date+Extension.swift
- Health/Presentation/Calendar/CalendarViewController.swift
- Health/Presentation/Dashboard/Content/Enum/DashboardCardKind.swift
- Health/Presentation/Dashboard/DashboardViewController.swift
- Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
- Health/Services/PromptBuilderService/DefaultPromptBuilderService.swift
- Health/Services/StepSync/StepSyncService.swift
- Health/ViewModels/AlanViewModel.swift
- Health/ViewModels/Dashboard/DashboardViewModel.swift
- Health/ViewModels/EntityViewModels/DailyStepViewModel.swift
- 캘린더에서 대시보드로 이동 시, 데이터가 불러오지 못하는 문제를 수정하였습니다.
- 날짜가 바뀌면 대시보드에서 해당 일에 맞는 정확한 목표 걸음 수를 가져오지 못하는 문제를 수정하였습니다.
- 나이대 별로 `보행 속도` 기준점을 수정하였습니다. (막대 프로그래스 바의 정확성을 위해)
- 캘린더에서 이동한 대시보드 화면에서 Pull-to-Refresh 시, 기준 날짜가 엉뚱하게 표시되는 문제 수정하였습니다.
---
| 1  | 2   |
| :-:| :-: |
|  <img width="1179" height="2556" alt="IMG_0546" src="https://github.com/user-attachments/assets/1deae6c1-aa52-465b-9004-db540f5f75f1" />  |   <img width="1179" height="2556" alt="IMG_0547" src="https://github.com/user-attachments/assets/9bdeca42-b8f4-4a2e-bef2-8011ad600cc3" />  |
|  <img width="1179" height="2556" alt="IMG_0548" src="https://github.com/user-attachments/assets/840637ff-ccf3-47cd-9604-8ff80d5cc4d5" />  |   <img width="1179" height="2556" alt="IMG_0549" src="https://github.com/user-attachments/assets/92040bc9-4f4c-408 …
> feat: 날짜가 바뀌면 정확한 목표 걸음 수를 제대로 가져오지 못하는 문제 수정

- Health/Core/Protocols/Alertable.swift
- Health/Presentation/Profile/BodyInfoViewController.swift
- 아이패드 가로모드일때 얼럿 높이조절 해서 여백을 줄였습니다
---
- 
---
- 
---
---
-
> feat: iPad 가로일때 Alert Height 조절

- Health/Presentation/Calendar/Views/CalendarDateCell.swift
- Health/Resources/Assets.xcassets/calendarDateStrokeColor.colorset/Contents.json
- 다크모드일 때도 달력 날짜 셀에 테두리 추가
- 테두리와 프로그레스 바의 너비 일치시키기
| Before | After |
| -- | -- |
| <img width="331" height="344" alt="image" src="https://github.com/user-attachments/assets/ece125b6-0e8b-44be-abca-49010b812eb5" /> | <img width="340" height="348" alt="image" src="https://github.com/user-attachments/assets/54b8a758-c229-4797-b25f-7992a6e93a38" /> |
> fix: 캘린더 탭 달력 날짜 셀에 다크모드일 때도 테두리 스트로크 추가

- Health/Presentation/Personal/PersonalViewController.swift
- Health/Presentation/Personal/Views/MainView/WalkingFilterCell.swift
---
- 위치 권한 없을 때 가까운 순 필터링 버튼을 비활성화 했습니다.
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
https://github.com/user-attachments/assets/8401384b-5575-4d71-8e14-d8c27c077566
|    |     |
---
-
> fix:Personal-위치권한 없을 때 가까운순 필터링 비활성화
