rlarjsdn3/EST-Soft-Team3-3rd-Project

Health.xcodeproj/project.pbxproj, Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Health.xcodeproj/xcshareddata/xcschemes/Health-DEBUG.xcscheme, Health/Application/AppDelegate.swift, Health/Presentation/Home/HomeViewController.swift, Health/Resources/GoogleService-Info.plist
> ex) close#6
---
- Firebase Crashlytics 추가
=> feat: Firebase Crashlytics 추가

Health/Presentation/Home/HomeViewController.swift
- 오타로 인한 문법 에러 때문에 빌드 에러가 발생한 부분을 수정했습니다. 
| Before  | After |
| -- | -- |
| <img width="925" height="419" alt="image" src="https://github.com/user-attachments/assets/d3acb536-1a07-4d48-8fb9-cf121061a6ed" /> | <img width="858" height="368" alt="image" src="https://github.com/user-attachments/assets/6f24792d-8b55-4d05-a204-c340a114be98" /> |
=> fix: Syntax 에러로 인한 빌드 에러 수정

Health/Core/Protocols/ToastPresentable.swift, Health/Core/Protocols/Toastable.swift
=> feat: Toast protocol

Health/Presentation/Onboarding/GenderSelectViewController.swift, Health/Presentation/Onboarding/HeightViewController.swift, Health/Presentation/Onboarding/Onboarding.storyboard, Health/Presentation/Onboarding/OnboardingViewController.swift, Health/Presentation/Onboarding/SelectAgeViewController.swift, Health/Presentation/Onboarding/WeightViewController.swift
> #22 
---
- 키, 체중, 나이, 성별 선택화면 초기구현 
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 온보딩 UI 몸무게, 키 입력화면 추가 작업 구현

Health/Presentation/Calendar/Calendar.storyboard, Health/Presentation/Calendar/CalendarViewController.swift, Health/Presentation/Calendar/Views/CalendarMonthCell.swift
- `CalendarViewController.swift` 추가 및 `CompositionalLayout` 설정
- `Views/CalendarMonthCell.swift` 추가
- [노션 태스크](https://www.notion.so/oreumi/ViewController-Layout-245ebaa8982b80ada0e2d4e457b497c8?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
=> feat: 캘린더 ViewController 추가 및 Layout 설정

Health/Core/Utils/Extensions/Date+Extension.swift, Health/Presentation/Calendar/CalendarViewController.swift, Health/Presentation/Calendar/Views/CalendarDateCell.swift, Health/Presentation/Calendar/Views/CalendarDateCell.xib, Health/Presentation/Calendar/Views/CalendarMonthCell.swift, Health/Presentation/Calendar/Views/CalendarMonthCell.xib
- 각 날짜를 나타내는 `CalendarDateCell` 추가
| Before | After | 디자인 시안 |
| -- | -- | -- |
| <img width="603" height="1311" alt="simulator_screenshot_B4125E6C-F4A7-467F-9BF6-900602763567" src="https://github.com/user-attachments/assets/a3492f89-c045-4dd2-8c40-16d59445084b" /> | <img width="603" height="1311" alt="simulator_screenshot_65B79B4E-AABA-48A4-9306-EB05852F5D54" src="https://github.com/user-attachments/assets/d8ee0ca9-edbf-4680-b40c-0a9fdedbe40f" /> | <img width="603" height="1311" alt="image" src="https://github.com/user-attachments/assets/a211d8bd-8a25-4c67-a466-7ba101ba80dc" /> |
> 일단 현재 월에 해당하지 않는 날짜는 표시하지 않음
- [노션 태스크](https://www.notion.so/oreumi/245ebaa8982b8064b203f9647b7d74bc?source=copy_link)
=> feat: 캘린더 탭 달력에 날짜 추가

Health/Presentation/Onboarding/Onboarding.storyboard, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/GenderSelectViewController.swift, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/HealthLinkViewController.swift, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/HeightViewController.swift, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/InputAgeViewController.swift, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/OnboardingViewController.swift, Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/WeightViewController.swift, Health/Resources/Info.plist
> ex) #41 #30 
---
- 기존: 키보드 입력을 마쳐도 dismiss가 안됨
- 현재: 키보드 입력 마쳤을때, dismiss되면서 키패드가 내려감 
---
---
- 
---
---
-
=> feat: healthApp-link UI만 구현 + 키보드 로직 수정

Health/ViewModels/EntityViewModels/DailyStepViewModel.swift, Health/ViewModels/EntityViewModels/GoalStepCountViewModel.swift
- DailyStepViewModel.swift
- `upsertDailyStep()`: 날짜 기준으로 DailyStep을 저장 또는 업데이트
- `fetchMissingDates(until:)`: 마지막 저장 날짜 이후 누락된 날짜 반환
- GoalStepCountViewModel.swift
- `goalStepCount(for:)`: 주어진 날짜에 가장 가까운 유효 목표(step goal) 조회
- StepSyncViewModel.swift 추가
- SceneDelegate.swift 에서 실행 → 데이터 동기화
- [노션 태스크](https://www.notion.so/oreumi/248ebaa8982b8096bc32e82b582c5e1a?v=241ebaa8982b807d8175000ce30f2bd1&source=copy_link)
=> feat: 걸음 데이터 동기화에 필요한 일부 메서드 추가

Health/Presentation/Personal/PersonalViewController.swift, Health/Presentation/Personal/Views/Content/PersonalContent.swift, Health/Presentation/Personal/Views/MainView/AISummaryCell.swift, Health/Presentation/Personal/Views/MainView/AISummaryCell.xib, Health/Presentation/Personal/Views/MainView/MonthSummaryCell.swift, Health/Presentation/Personal/Views/MainView/MonthSummaryCell.xib, Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.xib, Health/Presentation/Personal/Views/MainView/WalkingFilterCell.xib, Health/Presentation/Personal/Views/MainView/WeekSummaryCell.xib, Health/Resources/Info.plist
---
- 분석 부분에 AI 요약 셀 추가
- info.plist에서 TLSv1.1에서 1.2로 버전 수정
- 추천 리스트 부분에서 버튼크기 수정
- 카드 배경색 box컬러로 변경
---
- 
---
--다음 할일--
- healthkit 연동된 일주일 데이터 한달데이터 불러와서 화면에 적용
- 일주일 데이터를 통해 막대 차트 그리기
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> Feat: 분석부분에 AI 요약 셀 추가 및 전반적인 UI 수정

Health/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
---
-  다크모드 일때, 채도 낮춘 AccentColor 변경
---
=> design: 다크모드 때 악센트 컬러 추가

Health.xcodeproj/project.pbxproj, Health/Core/ViewControllers/HealthTabBarController.swift, Health/Presentation/Personal/PersonalViewController.swift, Health/Presentation/Personal/Views/Content/PersonalContent.swift, Health/Presentation/Personal/Views/MainView/AISummaryCell.xib, Health/Presentation/Personal/Views/MainView/MonthSummaryCell.swift, Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.xib, Health/Presentation/Personal/Views/MainView/WalkingFilterCell.swift, Health/Presentation/Personal/Views/MainView/WalkingFilterCell.xib, Health/Presentation/Personal/Views/MainView/WeekSummaryCell.swift, Health/Services/CourseService/LocationPermissionService.swift, Health/ViewModels/EntityViewModels/HealthDataViewModel.swift, Health/ViewModels/EntityViewModels/PersonalViewModel.swift
---
- 앱 설치시 처음 맞춤 탭 버튼 누르면 위치 권한 설정 할 수 있게 구현
- Alert는 필터 버튼중 가까운순을 클릭 했을때 Alert를 한번만 띄웁니다.
-앱에서 나갔다가 다시 들어와서 가까운순 클릭하면 또 다시 Alert를 띄워줍니다
-> 기본 정렬을 코스길이순으로 변경하여 가까운순 버튼을 클릭하지만 않으면 알림창은 뜨지 않습니다.
- 위치 권한을 허용하지 않은채로 앱사용시 추천코스 셀 오른쪽에 위치권한이 없습니다 라고 표시됩니다.
- 위치권한을 허용하면 내위치로 부터 걷기 코스가 몇 키로 떨어져 있는지 표시할 예정입니다.
-피드백 반영(싱글톤,변수명 수정, import TsAlert를 탭바컨트롤러에서 PersonalViewcontroller로 변경)
---
- 
---
- 수정완료
- 뷰모델과 뷰컨트롤러로 분리하여 리팩토링 하려고 하였으나 실패했습니다..
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat:앱 초기 설치시 맞춤 탭 버튼 눌렀을 때 위치권한 설정 할 수 있게 구현(피드백 반영)

Health/Presentation/Personal/PersonalViewController.swift, Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.swift, Health/Presentation/Personal/Views/MainView/RecommendPlaceCell.xib, Health/Services/CourseService/LocationPermissionService.swift, Health/Services/CourseService/WalkingCourseService.swift, Health/ViewModels/EntityViewModels/CourseDistanceViewModel.swift
---
- 현재 나의 위치와 추천코스와의 거리 표시
---
- 
---
- 위치권한 허용하지 않았을 때 위치권한 없음Label이 표시됩니다.
- 네트워크 연결 실패시에는 썸네일은 기본 SF심볼로 표시하고 위치 Label은 네트워크 오류로 표시됩니다.
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> Feat:내위치와 코스와의 거리 계산

Health/Application/SceneDelegate.swift, Health/Core/Storage/UserDefaults/UserDefaultsKeys.swift, Health/Presentation/Profile/Profile.storyboard, Health/Presentation/Profile/ProfileViewController.swift, Health/Presentation/Profile/Views/DisplayModeView.swift
- 프로필 탭에서 화면모드 설정과 문의하기 기능 추가
---
- 이메일 받는 주소는 팀장님인 건우님 이메일로 했습니다.
---
---
-
=> feat: ProfileView에서 화면모드, 메일보내기 추가

Health/Core/Storage/UserDefaults/UserDefaultsKeys.swift
=> fix: 문법 에러 수정

Health/Presentation/Personal/PersonalViewController.swift, Health/Services/CourseService/LocationPermissionService.swift, Health/ViewModels/EntityViewModels/CourseDistanceViewModel.swift
---
- 가까운순 버튼 클릭시 사용자와 나의 위치가 가까운 순으로 정렬됩니다.
- 위치권한 허용 안할시 위치권한 없음 Label은 추천코스 셀이 재사용될때 표시됩니다.
- 앱 껐다가 켰을때 위치권한 없음 Label 뜨던 버그 수정했습니다.
---
- 
---
- 위치권한을 계속 껐다 켰다 하는거 아닌 이상 어색해 보이지는 않아보입니다.
- 다음 할일은 Alan에게 사용자 코스 난이도 받아오는 작업입니다. PR 머지되면 작업 바로 시작 하겠습니다. 
- 영상 화질 안좋은점 양해부탁드립니다~
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 코스 가까운순 정렬 구현 및 버그 fix

Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift, Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBarDelegate.swift, Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBarItem.swift, Health/Core/Utils/Extensions/UIImage+Extension.swift, Health/Core/Utils/Extensions/UIView+Extension.swift
[Notion Task](https://www.notion.so/oreumi/HealthNavigationBar-254ebaa8982b80dda32ccc64a1b176ef?source=copy_link)
- `HealthNavigationBar` 및 부가 코드(`HealthNavigationBarItem` 등)을 작성하였습니다.
- 이미지 리사이징을 도와주는 `resized(width:)` 메서드를 작성하였습니다.
- 뷰(UIView)에서 상위 뷰-컨트롤러를 찾아주는 `findAvailableViewController()` 메서드를 작성하였습니다.
- 모달 시트에서 네비게이션 바가 제대로 표시되지 않는 문제를 수정하였습니다 **`수정 #1`**
---
- 자세한 사용법은 노션 및 디스코드에 올려드린 예제 코드를 참고해주세요~
=> feat: `HealthNavigationBar` 코드 작성, 이미지 리사이징 함수 및 상위 뷰-컨트롤러를 찾아주는 함수 코드 작성 (수정 #1)

Health/Presentation/Profile/BodyInfoViewController.swift, Health/Presentation/Profile/Views/EditBirthdayView.swift
- CoreData에서 Age를 불러와서 태어난 해를 구해서 표시합니다
---
- 
---
- 도현님 코드 삭제
---
-
=> feat: CoreData에 저장되어있는 Age를 가져와서 태어난 해를 구해서 표시합니다

Health.xcodeproj/project.pbxproj, Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Health/Core/Protocols/Alertable.swift
- `TSAlertController` 패키지를 v1.1.0에서 v1.1.1로 업데이트하였습니다.
---
- 제목 레이블이 위아래로 과도하게 늘어나는 문제 해결했습니다~
---
| 1  | 2   |
| :-:| :-: |
|  <img width="948" height="904" alt="스크린샷 2025-08-22 오후 3 28 27" src="https://github.com/user-attachments/assets/3a8dec85-af3c-4665-8cbb-79ce5a0d1560" />  |  <img width="1179" height="2556" alt="IMG_0500" src="https://github.com/user-attachments/assets/c4cec46b-2e93-4abe-b73e-8a23c7ad545e" />   |
=> feat: TSAlertController 패키지 업데이트, `Alertable` 코드 최적화

Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift, Health/Presentation/Onboarding/MainVC/OnboardingViewController.swift, Health/Presentation/Onboarding/Onboarding.storyboard
> 
---
- 온보딩 하단 설명 폰트 caption1 -> callout 
- 이미지 위치조정을 위한 스페이싱 조정 40 -> 20
- 각 입력 ui별 제목 레이블 폰트사이즈 조정  body -> system semibold 20 
- 건강앱 연동 멘트 수정 
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 온보딩 QA 피드백 UI 수정 (여백 수정, 폰트크기 수정 등)

Health.xcodeproj/project.pbxproj, Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- 빌드 설정(번들ID 관련) 및 TSAlertController 패키지 버전 수정
=> feat: 빌드 설정 및 TSAlertController 패키지 버전 수정

Health/Core/Protocols/Alertable.swift, Health/Core/Utils/Extensions/UILabel+Extension.swift, Health/Presentation/Profile/BodyInfoViewController.swift, Health/Presentation/Profile/ProfileViewController.swift, Health/Presentation/Profile/Views/DisplayModeView.swift, Health/Presentation/Profile/Views/EditBirthdayView.swift, Health/Presentation/Profile/Views/EditDiseaseView.swift, Health/Presentation/Profile/Views/EditGenderView.swift, Health/Presentation/Profile/Views/EditHeightView.swift, Health/Presentation/Profile/Views/EditStepGoalView.swift, Health/Presentation/Profile/Views/EditWeightView.swift
-  액션시트 크기 변경
- 액션시트 타이틀 폰트,위치 변경
- 태어난 해 PickerView에서 DefaultPick을 보이는 년도로 수정
- 질병 CollectionView 스크롤 비활성화
- 목표걸음 수 버튼 하이라이트 변경
- PicekrView 아이패드 높이 수정
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 프로필뷰 QA 일부분 수정

Health/Presentation/Profile/ProfileViewController.swift
- 신체 정보 셀을 터치하고 FaceID 인증중일때는 터치 안되도록 막았습니다
- 인증실패시 경고토스트 삭제
---
-
---
- 인증 불가(인증실패랑 다름. faceid나 비밀번호가 설정 안되어있을때) 일때는 경고토스트 나옴
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: ProfileView에서 FaceID 인증중일때는 셀 터치 안되도록 수정(2번 클릭해서 인증실패 막기위함)

Health/Core/Protocols/Alertable.swift, Health/Presentation/Profile/BodyInfoViewController.swift, Health/Presentation/Profile/ProfileViewController.swift, Health/Presentation/Profile/Views/Cells/EditDiseaseCollectionViewCell.swift, Health/Presentation/Profile/Views/DisplayModeView.swift, Health/Presentation/Profile/Views/EditBirthdayView.swift, Health/Presentation/Profile/Views/EditDiseaseView.swift, Health/Presentation/Profile/Views/EditHeightView.swift, Health/Presentation/Profile/Views/EditWeightView.swift
- 신체정보 Action Sheet Inset 수정
- 질병 -> 지병으로 수정
- 지병 cell 에서 border 제거
- 건강 권한 킬때 alert 공통으로 수정
- 메일 보냈을때 안내 Toast 공손하게 수정
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 프로필뷰 UI 수정

Health/Presentation/Profile/ProfileViewController.swift, Health/Presentation/Profile/Views/EditStepGoalView.swift
- 걸음수 fontsize가 변경되는것 수정
- 걸음 수 변경되는 단위 100으로 수정
- 버튼 롱프레스 구현
- 버튼 햅틱 구현
---
- 실기기로 하셔야 햅틱 테스트 가능합니다
---
- 롱프레스는 서서히 가속됩니다
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 프로필뷰 목표걸음 변경 버튼 수정

Health/Presentation/Calendar/Views/CalendarDateCell.swift, Health/Services/StepSync/StepSyncService.swift, Health/ViewModels/Dashboard/DashboardViewModel.swift
@jseongee ⭐️⭐️⭐️
---
- (새벽 시간 대에 걸음 수 데이터가 없을 때) 앱 최초 실행 시, 목표 걸음 수가 제대로 출력되지 않는 문제를 수정하였습니다.
=> feat: 앱 최초 실행 시, 목표 걸음 수가 제대로 출력되지 않는 문제 수정

Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
> #203 
---
-  다음버튼 눌렀을때 경고창뜨던것 다시 스위치눌렀을때 뜨는거로 원상복구
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 권한 로직 원상복구

Health/Presentation/Calendar/CalendarViewController.swift
건강 앱에서 "걸음" 연동만 껐을 때, 달력에 여전히 데이터가 표기되는 문제가 있어,
포그라운드 상태가 되면 "걸음"에 대해서만 연동이 되었는지 확인하도록 했습니다.
[노션 - QA](https://www.notion.so/oreumi/25cebaa8982b80c68af4cb4418b07b2d?v=242ebaa8982b8158aea0000cba0038c6&source=copy_link)
=> fix: 건강 앱에서 “걸음” 연동만 껐을 때 달력에 데이터 표시되는 문제 수정

Health/Core/Utils/Extensions/Array+Extension.swift, HealthTests/Core/Extensions/ArrayExtensionTests.swift, HealthTests/Core/Extensions/DateExtensionsTests.swift, HealthTests/Core/Extensions/DoubleExtensionTests.swift
>
---
-  extension - array, date, double 단위테스트코드 작성완료
- array extension 코드 부호 수정 (|| -> &&)
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: extension - array, date, double 단위테스트코드 작성완료

Health/Presentation/Profile/ProfileViewController.swift
- 건강 권한 스위치 관련 Notification 수정
- Alert 문구 수정
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> fix: 프로필 notification 수정

Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift, Health/Presentation/Onboarding/Onboarding.storyboard, Health/Presentation/Onboarding/SubVC/YearTextField.swift
---
- yearTextField Subclass 추가후 반영 (단위레이블 옆으로 밀리는 현상 수정하기위해 필요)
- 년도 범위 수정 (1900~2024)
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: yearVC 단위레이블 옆으로 밀리는 현상 수정 + 범위 수정

Health/Presentation/Onboarding/MainVC/GenderSelectViewController.swift, Health/ViewModels/EntityViewModels/UserInfoViewModel.swift
---
- UserInfoVM saveUser매서드 주석처리 (주석처리후 시뮬, 실기기 정상작동되는것확인, 사용하시는분 있으시면 코멘트 남겨주세요) 
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 성별버튼 비활성화 상태 색상 변환 (boxBG -> systemGray5)

Health/ViewModels/EntityViewModels/CourseDistanceViewModel.swift, Health/ViewModels/EntityViewModels/LLMRecommendationViewModel.swift, Health/ViewModels/EntityViewModels/PersonalViewModel.swift, HealthTests/ViewModels/Personal/LLMRecommendationViewModelTests.swift, HealthTests/ViewModels/Personal/WeekSummaryCellViewModelTest.swift
---
-테스트 코드 작성-
- 건강권한 테스트
- 추천난이도 파싱 테스트
- 추천난이도 캐시 테스트
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> test:테스트 코드 작성(맞춤케어 뷰)

HealthTests/ViewModels/EditBirthdayViewTests.swift, HealthTests/ViewModels/EditHeightViewTests.swift, HealthTests/ViewModels/EditStepGoalViewTests.swift
- 테스트 코드 추가했습니다.
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: ProfileView 테스트 코드 작성

Health/Core/Utils/Extensions/Date+Extension.swift, Health/ViewModels/Dashboard/DashboardViewModel.swift
오후 12:37 커밋 수정함
(테스트 코드가 아닌 뷰-모델 코드 수정)
혹시나 제가 없다면 병합 부탁드립니다!
=> feat: `DashboardViewModel` 미립자 수정

Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift, Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift, Health/Presentation/Onboarding/MainVC/WeightViewController.swift, Health/Presentation/Onboarding/Onboarding.storyboard, HealthTests/Core/Extensions/DateExtensionsTests.swift
---
- 어제 년도랑 같이 작업해놨었는데 몸무게로직이 35~200 그대로길래 다시 고쳤습니다 
- 테스트 코드 에러 생긴거 확인후, 고쳤습니다
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: QA extension XCTest fix + weight fix

Health/Models/CoreData/Entities/DailyStepEntity+CoreDataProperties.swift, Health/Models/CoreData/Entities/GoalStepCountEntity+CoreDataProperties.swift, Health/Models/CoreData/Entities/UserInfoEntity+CoreDataProperties.swift, Health/Presentations/Onboarding/Content/Enum/Disease.swift, Health/Presentations/Onboarding/Delegates/CustomOnboardingNaviBarView.swift, Health/Presentations/Onboarding/OnboardingViewController.swift, Health/Presentations/Onboarding/Views/DynamicWidthTextField.swift, Health/Presentations/Onboarding/Views/ProgressIndicatorStackView.swift, Health/Presentations/Onboarding/Views/YearTextField.swift
>
---
- 온보딩 문서 일부에 문서화 주석 추가 
---
- 
---
- 
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> feat: 온보딩 서브뷰, 배열 + 코어데이터 attributes 문서화 주석 생성

Health/Presentations/Profile/BodyInfoViewController.swift, Health/Presentations/Profile/ProfileViewController.swift, Health/Presentations/Profile/Views/EditBirthdayView.swift, Health/Presentations/Profile/Views/EditDiseaseView.swift, Health/Presentations/Profile/Views/EditStepGoalView.swift
- 주석 정리 및 문서화
---
| 1  | 2   |
| :-:| :-: |
|    |     |
---
-
=> refactor:주석 및 docc 정리

Health/Presentations/Calendar/CalendarViewController.swift, Health/Presentations/Calendar/Views/CalendarProgressBar.swift, Health/Presentations/Calendar/Views/Cells/CalendarDateCell.swift, Health/Presentations/Calendar/Views/Cells/CalendarMonthCell.swift
- 캘린더 관련 파일들에 DocC 주석을 추가합니다.
- 로직 변경은 없습니다.
=> docs: 캘린더 관련 파일들에 DocC 주석 추가
